version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Projects/Lcventures
hooks:
  BeforeInstall:
    - location: permissions.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: stop.sh
      timeout: 300
      runas: root

